/**
 * Project settings.
 */

const DASHBOARD_CONFIG = Object.freeze({
  SPREADSHEET_ID: '',
  SALES_SHEET: 'CATEGORY OF SALES V2',
  EXPENSE_SHEET: 'DISBURSEMENT',
  TARGET_SHEET: ' slsTGT',
  CUSTOMER_SHEET: 'CUSTOMER TYPE V2',
  TITLE: 'TL Mabuhay Driving School Performance Dashboard',
  DEFAULT_WINDOW: 'LATEST_MONTH',
  AUTO_REFRESH_MINUTES: 0,
  SOURCE_CACHE_SECONDS: 15 * 60,
  SOURCE_CACHE_VERSION: '2026-08-05-new-slsach-source-v6',
  RESULT_CACHE_SECONDS: 15 * 60,
  RESULT_CACHE_VERSION: '2026-08-05-new-slsach-results-v12',
  CACHE_CHUNK_CHARACTERS: 70000,
  CACHE_WRITE_BATCH_SIZE: 20,
  CACHE_LOCK_TIMEOUT_MS: 12000
});
